- name: Check access on Palo Alto firewall
  hosts: localhost
  gather_facts: no
  vars:
    json_data: "{{ lookup('file', 'playbooks/input.json') | from_json }}"
    palo_alto_provider:
      username: "admin"
      password: "ICICI1@src"
      ip_address: "11.0.0.200"

  tasks:
    - name: List files in the playbooks directory
      find:
        paths: "./playbooks"
        file_type: file
      register: playbook_files

    - name: Print list of files in playbooks directory
      debug:
        msg: "{{ playbook_files.files | map(attribute='path') | list }}"

    - name: Print the parsed JSON data
      debug:
        msg: "{{ json_data }}"

    - name: Gather all security rules from the Palo Alto firewall
      paloaltonetworks.panos.panos_security_rule_facts:
        provider: "{{ palo_alto_provider }}"
      register: security_rules

    - name: Debug the security rules fetched
      debug:
        msg: "{{ security_rules }}"

    - name: Initialize access_in_place variable
      set_fact:
        access_in_place: false

    - name: Check each security rule
      set_fact:
        access_in_place: true
      when: |
        item.source == json_data.src and
        item.destination == json_data.dst and
        json_data.port in item.service
      loop: "{{ security_rules.panos_security_rule_facts }}"
      loop_control:
        label: "{{ item.name }}"
      notify:
        - Stop further checking

    - name: Print access status
      debug:
        msg: |
          {% if access_in_place %}
            Access in place for src={{ json_data.src }} to dst={{ json_data.dst }} on port {{ json_data.port }}.
          {% else %}
            No access in place for src={{ json_data.src }} to dst={{ json_data.dst }} on port {{ json_data.port }}.
          {% endif %}
      
  handlers:
    - name: Stop further checking
      meta: end_play
