---
- name: Check access on Palo Alto firewall
  hosts: localhost
  gather_facts: no

  vars:
    # Read and parse the JSON file
    json_data: "{{ lookup('file', 'playbooks/input.json') | from_json }}"
    palo_alto_provider:
      hostname: "11.0.0.200"
      username: "admin"
      password: "ICICI1@src"
      api_key: null

  tasks:
    - name: List files in the playbooks directory
      shell: ls playbooks
      register: playbook_files

    - name: Print list of files in playbooks directory
      debug:
        var: playbook_files.stdout_lines

    - name: Print the parsed JSON data
      debug:
        var: json_data

    - name: Gather all security rules from the firewall
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ palo_alto_provider }}"
        state: "gathered"
        gathered_filter:
          - all
      register: security_rules

    - name: Print all gathered security rules
      debug:
        var: security_rules.rules

    - name: Check if the src to dst access matches any rule
      set_fact:
        matching_rules: >-
          {{
            security_rules.rules |
            selectattr('source', 'search', json_data.src) |
            selectattr('destination', 'search', json_data.dst) |
            selectattr('service', 'contains', json_data.port | string) |
            list
          }}

    - name: Print matched rules
      debug:
        msg: >
          {% if matching_rules %}
            Found matching rules:
            {% for rule in matching_rules %}
              - Name: {{ rule.name }}, Source: {{ rule.source }}, Destination: {{ rule.destination }}, Service: {{ rule.service }}
            {% endfor %}
          {% else %}
            No matching rules found for src={{ json_data.src }}, dst={{ json_data.dst }}, and port={{ json_data.port }}.
          {% endif %}
