- name: Check access on Palo Alto firewall
  hosts: localhost
  gather_facts: no
  vars:
    json_data: "{{ lookup('file', 'playbooks/input.json') | from_json }}"
    palo_alto_provider:
      username: "admin"
      password: "ICICI1@src"
      ip_address: "11.0.0.200"

  tasks:
    - name: List files in the playbooks directory
      find:
        paths: "./playbooks"
        file_type: file
      register: playbook_files

    - name: Print list of files in playbooks directory
      debug:
        msg: "{{ playbook_files.files | map(attribute='path') | list }}"

    - name: Print the parsed JSON data
      debug:
        msg: "{{ json_data }}"

    - name: Check if the src to dst access is in place
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ palo_alto_provider }}"
        state: gathered
        filter:
          src: "{{ json_data.src }}"
          dst: "{{ json_data.dst }}"
          application: "application-default"
          service: "{{ json_data.port }}"
      register: security_rule_facts

    - name: Debug security rule facts
      debug:
        msg: "{{ security_rule_facts }}"

    - name: Print access status
      debug:
        msg: |
          {% if security_rule_facts.panos_security_rule %}
            Access in place for src={{ json_data.src }} to dst={{ json_data.dst }} on port {{ json_data.port }}.
          {% else %}
            No access in place for src={{ json_data.src }} to dst={{ json_data.dst }} on port {{ json_data.port }}.
          {% endif %}
