---
- name: Gather address object groups from Palo Alto firewall
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get address object groups from the firewall
      paloaltonetworks.panos.panos_address_object:
        provider:
          ip_address: "11.0.0.200"
          username: "admin"
          password: "ICICI1@src"
      register: address_objects

    - name: Display address object groups
      debug:
        msg: "{{ address_objects }}"
