---
- name: Configure Firewall Rule on Palo Alto
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Add a security rule to Palo Alto Firewall
      panos_security_rule:
        provider:
          ip_address: "192.168.1.1"  # Replace with the IP address of your firewall
          username: "admin"         # Replace with your firewall username
          password: "password"      # Replace with your firewall password
          api_key: null             # Use API key instead of password if preferred
        rule_name: "Allow-HTTP"
        source_zone: ["trust"]
        source_address: ["any"]
        destination_zone: ["untrust"]
        destination_address: ["any"]
        application: ["web-browsing"]
        service: ["application-default"]
        action: "allow"
        description: "Allow HTTP traffic from trust to untrust zones"
        log_setting: "default"
        tag: ["ansible"]

    - name: Commit changes to Palo Alto Firewall
      panos_commit:
        provider:
          ip_address: "192.168.1.1"
          username: "admin"
          password: "ICICI1@src"
          api_key: null
