---
- name: Generate combinations of sources, destinations, and ports
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Define input variables
      set_fact:
        sources: 
          - "12.0.0.1"
          - "12.0.0.3"
        destinations: 
          - "13.0.0.1"
          - "13.0.0.4"
        ports:
          - "tcp:443"
          - "tcp:4444"
          - "udp:345"

    - name: Generate all combinations
      set_fact:
        combinations: >-
          {{
            sources | product(destinations) | map('product', ports) | map('flatten') | list
          }}

    - name: Print combinations
      debug:
        msg: "{{ item }}"
      with_items: "{{ combinations }}"
