---
- name: Fetch address objects from Palo Alto Firewall
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Retrieve address objects
      paloaltonetworks.panos.panos_address_object:
        provider:
          ip_address: 11.0.0.200  # IP of the Palo Alto firewall
          username: admin  # Replace with your username
          password: ICICI1@src  # Replace with your password
        state: query  # Use "query" to fetch the current address objects
      register: address_objects

    - name: Show address objects
      debug:
        var: address_objects
