---
- name: Gather address group objects from Palo Alto firewall
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get address group objects from the firewall
      paloaltonetworks.panos.panos_address_group:
        provider:
          ip_address: "11.0.0.200"
          username: "admin"
          password: "ICICI1@src"
      register: address_groups

    - name: Display address group objects
      debug:
        msg: "{{ address_groups }}"
