---
- name: Fetch address objects from Palo Alto Firewall
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Fetch address objects
      ansible.builtin.panos_object_facts:
        provider:
          ip_address: 11.0.0.200
          username: admin  # Replace with your username
          password: ICICI1@src  # Replace with your password
          api_key: ''      # Optionally, use an API key instead of username/password
        object_type: address
      register: address_objects

    - name: Display fetched address objects
      debug:
        var: address_objects
