---
- name: Gather address objects, address groups, and security rules from Palo Alto firewall
  hosts: localhost
  gather_facts: no
  vars:
    src: "12.0.0.1/32"
    dst: "13.0.0.1/32"

  tasks:
    - name: Get address objects from the firewall
      paloaltonetworks.panos.panos_address_object:
        provider:
          ip_address: "11.0.0.200"
          username: "admin"
          password: "ICICI1@src"
        state: gathered
        gathered_filter: "*"
      register: address_objects

    - name: Get address group objects from the firewall
      paloaltonetworks.panos.panos_address_group:
        provider:
          ip_address: "11.0.0.200"
          username: "admin"
          password: "ICICI1@src"
        state: gathered
        gathered_filter: "*"
      register: address_groups

    - name: Get parent address groups recursively
      set_fact:
        all_parent_groups: "{{ {} }}"

    - name: Build recursive parent groups lookup
      set_fact:
        all_parent_groups: >
          {{
            all_parent_groups | combine({
              item.name: address_groups.gathered | selectattr('static_value', 'contains', item.name) | map(attribute='name') | list
            })
          }}
      loop: "{{ address_groups.gathered }}"

    - name: Recursively find all parent groups
      vars:
        group_to_check: "{{ item }}"
      set_fact:
        resolved_groups: >
          {{
            (resolved_groups | default([])) + 
            [group_to_check] + 
            (all_parent_groups[group_to_check] | map('extract', all_parent_groups) | flatten | list | unique)
          }}
      loop: "{{ matched_address_groups.source + matched_address_groups.destination }}"
      when: group_to_check in all_parent_groups

    - name: Display final resolved groups
      debug:
        msg: "Resolved groups: {{ resolved_groups | unique }}"
