---
- name: Gather address objects, address groups, and security rules from Palo Alto firewall
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get address objects from the firewall
      paloaltonetworks.panos.panos_address_object:
        provider:
          ip_address: "11.0.0.200"
          username: "admin"
          password: "ICICI1@src"
        state: gathered
        gathered_filter: "*"
      register: address_objects

    - name: Get address group objects from the firewall
      paloaltonetworks.panos.panos_address_group:
        provider:
          ip_address: "11.0.0.200"
          username: "admin"
          password: "ICICI1@src"
        state: gathered
        gathered_filter: "*"
      register: address_groups

    - name: Get security rules from the firewall
      paloaltonetworks.panos.panos_security_rule:
        provider:
          ip_address: "11.0.0.200"
          username: "admin"
          password: "ICICI1@src"
        state: gathered
        gathered_filter: "*"
      register: security_rules

    - name: Display address objects
      debug:
        msg: "{{ address_objects }}"

    - name: Display address group objects
      debug:
        msg: "{{ address_groups }}"

    - name: Display security rules
      debug:
        msg: "{{ security_rules }}"
