---
- name: Pull all firewall policies from Palo Alto firewall
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Retrieve security policies from Palo Alto firewall
      paloaltonetworks.panos.panos_security_rule:
        provider:
          ip_address: 11.0.0.200
          username: admin
          password: ICICI1@src
        state: "gathered"
        gathered_filter: "*"
      register: security_rules

    - name: Display all firewall rules with details
      debug:
        msg: "{{ security_rules }}"
