---
- name: Gather PaloAlto Address Objects
  hosts: PA01
  gather_facts: false
  connection: local
  vars:
    ansible_python_interpreter: "/usr/bin/python3"  # Explicitly set the Python interpreter
    palo_cred:
      ip_address: 11.0.0.200  # IP of the Palo Alto firewall
      username: admin  # Replace with your username
      password: ICICI1@src  # Replace with your password
  tasks:
    - name: Gather Address Object
      paloaltonetworks.panos.panos_address_object:
        provider: "{{ palo_cred }}"
        state: gathered  # Gather existing address objects
      register: obj_details

    - name: Show Address Objects
      debug:
        msg: "{{ obj_details }}"
