---
- name: Test PaloAlto Connectivity
  hosts: PA01
  gather_facts: false
  vars:
    palo_cred:
      ip_address: 11.0.0.200
      username: admin
      password: ICICI1@src
  tasks:
    - name: Ping PaloAlto Firewall
      paloaltonetworks.panos.panos_ping:
        provider: "{{ palo_cred }}"
      register: ping_result

    - name: Show ping result
      debug:
        msg: "{{ ping_result }}"
